# Generated by Django 5.2.4 on 2025-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_middleware_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[
                ('gold', 'Gold'),
                ('silver', 'Silver'),
                ('bronze', 'Bronze')
            ], default='bronze', max_length=10),
        ),
    ]
